package com.handy.voice.audio

import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Plays PCM audio data generated by the TTS engine.
 */
@Singleton
class AudioPlayer @Inject constructor() {

    private var audioTrack: AudioTrack? = null

    /**
     * Play PCM float32 audio samples.
     *
     * @param audioData Float array of PCM samples (range [-1, 1])
     * @param sampleRate Sample rate in Hz (typically 24000 for TTS output)
     */
    fun play(audioData: FloatArray, sampleRate: Int = 24000) {
        stop()

        val bufferSize = AudioTrack.getMinBufferSize(
            sampleRate,
            AudioFormat.CHANNEL_OUT_MONO,
            AudioFormat.ENCODING_PCM_FLOAT,
        )

        audioTrack = AudioTrack.Builder()
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_MEDIA)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build()
            )
            .setAudioFormat(
                AudioFormat.Builder()
                    .setSampleRate(sampleRate)
                    .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
                    .setEncoding(AudioFormat.ENCODING_PCM_FLOAT)
                    .build()
            )
            .setBufferSizeInBytes(bufferSize.coerceAtLeast(audioData.size * 4))
            .setTransferMode(AudioTrack.MODE_STATIC)
            .build()

        audioTrack?.apply {
            write(audioData, 0, audioData.size, AudioTrack.WRITE_BLOCKING)
            play()
        }
    }

    fun stop() {
        audioTrack?.apply {
            try {
                stop()
            } catch (_: IllegalStateException) {
                // Already stopped
            }
            release()
        }
        audioTrack = null
    }

    fun isPlaying(): Boolean = audioTrack?.playState == AudioTrack.PLAYSTATE_PLAYING
}
